services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: ramazanyildirim-web

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    environment:
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "500"

    stdin_open: true
    tty: true

volumes:
  node_modules:
